#include "FLV_Cluster_APP.h"

void DisplayMenuPopup()
{
	DisplayMenuBackgroundBG();
	LCD_Draw_Color(6, 48, 210, 122, COLOR_MENU_GRAY);
}

void DisplayPopupStringComplete()
{
	if(OldScreenIndex != ScreenIndex) 
	{
		switch(ScreenIndex)
		{
			case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_COMPLETE:	
			case SCREEN_STATE_MENU_EQUIPMENT_MODELSELECT_CHANGE_COMPLETE:	
			case SCREEN_STATE_MENU_MAINTENANCE_USERPWCHANGE_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_ESL_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_LOADADJUST_UNLOAD_COMPLETE:	
			case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_LOADADJUST_LOAD_COMPLETE:			
			case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_LOADADJUST_INITIAL_COMPLETE:	
			case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_CROSSSECTION_INPUT_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_DCSR_MODE_COMPLETE:				
			case SCREEN_STATE_MENU_EQUIPMENT_DCSR_SPEED_BLOCKING_COMPLETE:			
			case SCREEN_STATE_MENU_EQUIPMENT_DCSR_SPEED_RESTORE_COMPLETE:	
			case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_MODE_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_SPEED_UP_COMPLETE:	
			case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_SPEED_DOWN_COMPLETE:	
			case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_OVERLAP_UP_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_OVERLAP_DOWN_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_MAXSPEEDLIMIT_FUNC_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_MAXSPEEDLIMIT_SPEED_SET_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_HAC_COMPLETE:		
			case SCREEN_STATE_MENU_EQUIPMENT_ZEROSTART_MODE_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_ZEROSTART_ACCEL_COMPLETE:	
			case SCREEN_STATE_MENU_EQUIPMENT_CLUTCHPROTECTION_SET_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_SEATBELTINTERLOCK_SET_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_SR_UP_COMPLETE:	
			case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_SR_DOWN_COMPLETE:

			case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_POSITION_LIFT_COMPLETE: 
			case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_POSITION_TILT_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_POSITION_AUX1_COMPLETE: 
			case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_POSITION_AUX2_COMPLETE:	
			case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_DEADZONE_LIFT_COMPLETE: 
			case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_DEADZONE_TILT_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_DEADZONE_AUX1_COMPLETE: 
			case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_DEADZONE_AUX2_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_LIFT_UP_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_LIFT_DOWN_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_TILT_A_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_TILT_B_COMPLETE:	
			case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_AUX1_A_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_AUX1_B_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_AUX2_A_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_AUX2_B_COMPLETE:				
				DisplayPopupString1((USHORT*)*StringSentence[INDEX_STR_COMPLETE]);
				break;
			case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_NOT_COMPLETE:	
			case SCREEN_STATE_MENU_EQUIPMENT_MODELSELECT_CHANGE_NOT_COMPLETE:
			case SCREEN_STATE_MENU_MAINTENANCE_USERPWCHANGE_NOT_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_ESL_NOT_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_LOADADJUST_UNLOAD_NOT_COMPLETE:	
			case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_LOADADJUST_INITIAL_NOT_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_CROSSSECTION_INPUT_NOT_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_DCSR_MODE_NOT_COMPLETE:		
			case SCREEN_STATE_MENU_EQUIPMENT_DCSR_SPEED_BLOCKING_NOT_COMPLETE:			
			case SCREEN_STATE_MENU_EQUIPMENT_DCSR_SPEED_RESTORE_NOT_COMPLETE:	
			case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_MODE_NOT_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_SPEED_UP_NOT_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_SPEED_DOWN_NOT_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_OVERLAP_UP_NOT_COMPLETE:	
			case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_OVERLAP_DOWN_NOT_COMPLETE:	
			case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_SR_UP_NOT_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_SR_DOWN_NOT_COMPLETE:	
			case SCREEN_STATE_MENU_EQUIPMENT_MAXSPEEDLIMIT_FUNC_NOT_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_MAXSPEEDLIMIT_SPEED_SET_NOT_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_HAC_NOT_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_ZEROSTART_MODE_NOT_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_ZEROSTART_ACCEL_NOT_COMPLETE:	
			case SCREEN_STATE_MENU_EQUIPMENT_CLUTCHPROTECTION_SET_NOT_COMPLETE:
			case SCREEN_STATE_MENU_EQUIPMENT_SEATBELTINTERLOCK_SET_NOT_COMPLETE:
				DisplayPopupString1((USHORT*)*StringSentence[INDEX_STR_NOT_COMPLETE]);
				break;
			case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_LOADADJUST_LOAD_NOT_COMPLETE:
				DisplayPopupString1((USHORT*)*StringSentence[45]);
				break;
		}
	}
}

void DisplayPopupString1(USHORT *s)
{
	DisplayMenuPopup();
	DisplayMultiLineCenterStringAt(s, 6, 48,  210, 122, gui_font23, COLOR_WHITE);	
	DrawMenuFull();
}

void DisplayPopupString2(USHORT *s1, USHORT *s2)
{
	DisplayMenuPopup();
	USHORT subbuf[100];
	USHORT length = 0, c;
	memset(&subbuf, 0x00, sizeof(subbuf));
	
	subbuf[length++] = (*s1++);
	c = subbuf[length-1];
	while((c != 0))
	{
		subbuf[length++] = (*s1++);
		c = subbuf[length-1];
	}
	
	subbuf[length-1] = 0x20;

	subbuf[length++] = (*s2++);
	c = subbuf[length-1];

	while((c != 0))
	{
		subbuf[length++] = (*s2++);
		c = subbuf[length-1];
	}	
	DisplayMultiLineCenterStringAt(&subbuf[0], 6, 48,  210, 122, gui_font23, COLOR_WHITE);	// ????????????.
	DrawMenuFull();
}


