#include "FLV_Cluster_APP.h"

UINT32 CurScreenIndex = 0;
UINT32 OldCurScreenIndex = 0xff;

extern UCHAR gMaintenanceItem;
extern EEPROM_MODEL_DATA1 InfoModel1;

void DisplayMenuBackgroundIcon()
{
	unsigned int top_index = (ScreenIndex & 0x0FFFFFFF); 
	if(top_index == 0)
	{
		PCXtoBMP_16bit(6, 6, 30, 27, FL_Image.menu_icon);
	}
	else
	{
		switch(ScreenIndex & 0xF0000000)
		{
			case SCREEN_STATE_MENU_EQUIPMENT_TOP:
				PCXtoBMP_16bit(6, 6, 30, 27, FL_Image.menu_icon_setting);
				break;			
			case SCREEN_STATE_MENU_MAINTENANCE_TOP:
				PCXtoBMP_16bit(6, 6, 30, 27, FL_Image.menu_icon_maintenance);
				break;			
			case SCREEN_STATE_MENU_DISPLAYSETTING_TOP:
				PCXtoBMP_16bit(6, 6, 30, 27, FL_Image.menu_icon_display);
				break;			
		}		
	}
	
}

void DisplayListPage(UCHAR nCurPage, UCHAR nTotalPage)
{
	LCD_Draw_Color(210, 48, 6, 128, COLOR_BLACK);
	if(nTotalPage == 2)
	{
		LCD_Draw_Color(210, 48+(62*(nCurPage-1)), 6, 61,  COLOR_MENU_SCROLL);
	}
	else if(nTotalPage == 3)
	{
		LCD_Draw_Color(210, 48+(31*(nCurPage-1)), 6, 61,  COLOR_MENU_SCROLL);
	}
	else if(nTotalPage <2)
		return;
	else
	{
		UCHAR height = 128/nTotalPage;
		LCD_Draw_Color(210, 48+(height*(nCurPage-1)), 6, height,  COLOR_MENU_SCROLL);
	}
}


void SetMarqueeTextViewTitle(UINT32 StringIndex)
{
	m_MarInfo.cntMarText = 0;
	m_MarInfo.SetInfo = 0;

	m_MarText[0].PictureX = 40;
	m_MarText[0].PictureY = 9;
	m_MarText[0].PictureWidth = 180;
	m_MarText[0].PictureHeight = 23;
	m_MarText[0].uwStartAddress = COLOR_BLACK;

	m_MarText[0].StringX= 40;
	m_MarText[0].StringY= 9;
	m_MarText[0].StringWidth = 180;
	m_MarText[0].FontSize = 23;
	m_MarText[0].StringColor = COLOR_WHITE;
	m_MarText[0].StringIndex = StringIndex;
	GetStringLength((USHORT*)*StringSentence[CurScreenIndex], gui_font23, m_MarText[0].StringWidth, &m_MarText[0].WidthLength, &m_MarText[0].MaxLength);
	
	m_MarInfo.cntMarText  = 1;
	
	m_MarInfo.SetInfo = 1;
}

void DisplayListTitleMenu()
{
	if((ScreenIndex == SCREEN_STATE_MENU_EQUIPMENT_TOP)
			|| (ScreenIndex == SCREEN_STATE_MENU_MAINTENANCE_TOP)
			|| (ScreenIndex == SCREEN_STATE_MENU_DISPLAYSETTING_TOP))
	{
		if((OldScreenIndex != SCREEN_STATE_MENU_EQUIPMENT_TOP)
			&& (OldScreenIndex != SCREEN_STATE_MENU_MAINTENANCE_TOP)
			&& (OldScreenIndex != SCREEN_STATE_MENU_DISPLAYSETTING_TOP))
		{
			DisplayBackground();
			DisplayMenuBackgroundIcon();
			if(OldScreenIndex < SCREEN_STATE_MENU_EQUIPMENT_TOP)
				OldCurScreenIndex = 0xffff;
			CurScreenIndex = 14;
		}
	}
	else
	{
		if((OldScreenIndex & 0x0FFFFFFF) == 0)
			DisplayMenuBackgroundIcon();
		
		if((ScreenIndex & 0xF0000000) == SCREEN_STATE_MENU_EQUIPMENT_TOP)
			DisplayListTitleEquipment();
		else if((ScreenIndex & 0xF0000000) == SCREEN_STATE_MENU_MAINTENANCE_TOP)
			DisplayListTitleMaintenance();
		else if((ScreenIndex & 0xF0000000) == SCREEN_STATE_MENU_DISPLAYSETTING_TOP)
			DisplayListTitleDsiplaySetting();
		
	}		

	USHORT width = 180;
	unsigned char SetMarquee;


	if(OldCurScreenIndex != CurScreenIndex)
	{
         OldCurScreenIndex = CurScreenIndex;
         //LCD_Draw_Color(40, 6, width, FONTSIZE_1, COLOR_BLACK);
         //GUI_DisplayLeftStringAt((USHORT*)*StringSentence[CurScreenIndex], 40, 6, width, COLOR_WHITE, FONTSIZE_1);
         LCD_Draw_Color(40, 9, width, FONTSIZE_2, COLOR_BLACK);
         SetMarquee = GUI_DisplayLeftStringAt((USHORT*)*StringSentence[CurScreenIndex], 40, 9, width, COLOR_WHITE, FONTSIZE_2);
         if((((CurScreenIndex >= 75) && (CurScreenIndex <= 77)) || ((CurScreenIndex >= 91) && (CurScreenIndex <= 93))
            || (CurScreenIndex == 24)|| (CurScreenIndex == 185)||(CurScreenIndex == 190)||(CurScreenIndex == 191)||(CurScreenIndex == 192) 
			||(CurScreenIndex == 20)||((CurScreenIndex >= 33) && (CurScreenIndex <= 38))|| (CurScreenIndex == 64)|| (CurScreenIndex == 65)
			|| (CurScreenIndex == 215) || (CurScreenIndex == 216) || (CurScreenIndex == 217)
		 	|| (CurScreenIndex == 67)|| (CurScreenIndex == 68)|| (CurScreenIndex == 205)|| ((CurScreenIndex >= INDEX_STR_MANAGEMENT) && (CurScreenIndex <= INDEX_STR_MANAGEMENT+MAINTENANCE_TOTAL-1))
            || ((CurScreenIndex >= INDEX_STR_MANAGEMENT_LPG) && (CurScreenIndex <= INDEX_STR_MANAGEMENT_LPG+3))|| (CurScreenIndex == INDEX_STR_MANAGEMENT_BRAKE_COOLING_OIL_FILTER)|| (CurScreenIndex <= 1)) && SetMarquee)
            SetMarqueeTextViewTitle(CurScreenIndex);
		 else
		 {
			memset(&m_MarText[0], 0x00, 10*sizeof(MarqueeTextView));
			memset(&m_MarInfo, 0x00, sizeof(MarqueeTextInfo));	 

		 }
	}
	else if((CurScreenIndex == 190)|| (CurScreenIndex == 205)|| (CurScreenIndex == 215) || (CurScreenIndex == 216) || (CurScreenIndex == 217)) //++,--, 201019 ysm
	{
		SetMarqueeTextViewTitle(CurScreenIndex);
	}		

}	


void DisplayListTitleEquipment()
{
	switch(ScreenIndex)
	{
		case SCREEN_STATE_MENU_MAINTENANCE_PW_POPUP:
		case SCREEN_STATE_MENU_EQUIPMENT_PW_POPUP:
			return;
	}
	switch(ScreenIndex)
	{
		case SCREEN_STATE_MENU_EQUIPMENT_TOP:			
			CurScreenIndex = 14;
			break;
		case SCREEN_STATE_MENU_EQUIPMENT_PW:				
			CurScreenIndex = 1;
			break;
		case SCREEN_STATE_MENU_EQUIPMENT_MODELSELECT_TOP:		
		case SCREEN_STATE_MENU_EQUIPMENT_TILTSETTING_TOP:						
		case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_TOP:		
		case SCREEN_STATE_MENU_EQUIPMENT_ESL_TOP:									
		case SCREEN_STATE_MENU_EQUIPMENT_DCSR_TOP:									
		case SCREEN_STATE_MENU_EQUIPMENT_HAC_TOP:		
		case SCREEN_STATE_MENU_EQUIPMENT_MAXSPEEDLIMIT_TOP:
		case SCREEN_STATE_MENU_EQUIPMENT_MACHINEINFO_TOP:		
		case SCREEN_STATE_MENU_EQUIPMENT_CLUTCHPROTECTION_TOP:
		case SCREEN_STATE_MENU_EQUIPMENT_ZEROSTART_TOP:
		case SCREEN_STATE_MENU_EQUIPMENT_SEATBELTINTERLOCK_TOP:
        case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_TOP:
		case SCREEN_STATE_MENU_EQUIPMENT_RMCU_TOP:		
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_TOP:	
			CurScreenIndex = 15;
			break;			
		case SCREEN_STATE_MENU_EQUIPMENT_MODELSELECT_INFO:		
		case SCREEN_STATE_MENU_EQUIPMENT_MODELSELECT_TYPE:
		case SCREEN_STATE_MENU_EQUIPMENT_MODELSELECT_TIRE:		
		case SCREEN_STATE_MENU_EQUIPMENT_MODELSELECT_CHANGE_POPUP:			
		case SCREEN_STATE_MENU_EQUIPMENT_MODELSELECT_CHANGE_COMPLETE:	
		case SCREEN_STATE_MENU_EQUIPMENT_MODELSELECT_CHANGE_NOT_COMPLETE:				
			CurScreenIndex = 18;
			break;
		case SCREEN_STATE_MENU_EQUIPMENT_MODELSELECT_MODEL:
			CurScreenIndex = 210;
			break;
			
		case SCREEN_STATE_MENU_EQUIPMENT_TILTSETTING_INITIAL:				
		case SCREEN_STATE_MENU_EQUIPMENT_TILTSETTING_INITIAL_COMPLETE:			
		case SCREEN_STATE_MENU_EQUIPMENT_TILTSETTING_INITIAL_NOT_COMPLETE:			
		case SCREEN_STATE_MENU_EQUIPMENT_TILTSETTING_END:						
			CurScreenIndex = 19;
			break;			
			
		case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_CROSSSECTION_TOP:						
		case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_LOADADJUST_TOP:					
		case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_DISPLAYSET_TOP:						
		case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_BUZZER_TOP:								
			CurScreenIndex = 20;
			break;			
		case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_CROSSSECTION_INPUT:					
		case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_CROSSSECTION_INPUT_COMPLETE:	
		case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_CROSSSECTION_INPUT_NOT_COMPLETE:	
		case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_CROSSSECTION_END:				
			CurScreenIndex = 33;
			break;			
		case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_LOADADJUST_UNLOAD_TOP:		
		case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_LOADADJUST_LOAD_TOP:				
		case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_LOADADJUST_INITIAL_TOP:			
			CurScreenIndex = 34;
			break;			
		case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_LOADADJUST_UNLOAD_INFO:	
		case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_LOADADJUST_UNLOAD_COMPLETE:			
		case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_LOADADJUST_UNLOAD_NOT_COMPLETE:	
		case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_LOADADJUST_UNLOAD_END:			
			CurScreenIndex = 37;
			break;			
		case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_LOADADJUST_LOAD_INPUT:			
		case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_LOADADJUST_LOAD_INFO:			
		case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_LOADADJUST_LOAD_COMPLETE:	
		case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_LOADADJUST_LOAD_NOT_COMPLETE:		
			CurScreenIndex = 38;
			break;			
		case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_LOADADJUST_INITIAL_SET:			
		case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_LOADADJUST_INITIAL_COMPLETE:			
		case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_LOADADJUST_INITIAL_NOT_COMPLETE:	
			CurScreenIndex = 39;
			break;			
		case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_DISPLAYSET_UNIT:						
		case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_DISPLAYSET_END:						
			CurScreenIndex = 35;
			break;			
		case SCREEN_STATE_MENU_EQUIPMENT_WEIGHTSENSOR_BUZZER_SET:								
			CurScreenIndex = 36;
			break;			
		case SCREEN_STATE_MENU_EQUIPMENT_ESL_CHANGE:								
		case SCREEN_STATE_MENU_EQUIPMENT_ESL_SET:									
		case SCREEN_STATE_MENU_EQUIPMENT_ESL_DELAYTIME_SELECT:			
		case SCREEN_STATE_MENU_EQUIPMENT_ESL_COMPLETE:							
		case SCREEN_STATE_MENU_EQUIPMENT_ESL_NOT_COMPLETE:					
			CurScreenIndex = 21;
			break;			
		case SCREEN_STATE_MENU_EQUIPMENT_DCSR_MODE_TOP:						
		case SCREEN_STATE_MENU_EQUIPMENT_DCSR_MODE_SET:						
		case SCREEN_STATE_MENU_EQUIPMENT_DCSR_MODE_COMPLETE:				
		case SCREEN_STATE_MENU_EQUIPMENT_DCSR_MODE_NOT_COMPLETE:		
		case SCREEN_STATE_MENU_EQUIPMENT_DCSR_MODE_END:						
		case SCREEN_STATE_MENU_EQUIPMENT_DCSR_SPEED_TOP:						
		case SCREEN_STATE_MENU_EQUIPMENT_DCSR_SPEED_BLOCKING_TOP:	
		case SCREEN_STATE_MENU_EQUIPMENT_DCSR_SPEED_BLOCKING_END:	
		case SCREEN_STATE_MENU_EQUIPMENT_DCSR_SPEED_RESTORE_TOP:			
		case SCREEN_STATE_MENU_EQUIPMENT_DCSR_SPEED_RESTORE_END:			
			CurScreenIndex = 22;
			break;			
		case SCREEN_STATE_MENU_EQUIPMENT_DCSR_SPEED_BLOCKING_SET:	
			CurScreenIndex = 64;
			break;			
		case SCREEN_STATE_MENU_EQUIPMENT_DCSR_SPEED_RESTORE_SET:			
			CurScreenIndex = 65;
			break;			

		case SCREEN_STATE_MENU_EQUIPMENT_HAC_SET:									
		case SCREEN_STATE_MENU_EQUIPMENT_HAC_COMPLETE:							
		case SCREEN_STATE_MENU_EQUIPMENT_HAC_NOT_COMPLETE:					
			CurScreenIndex = 23;
			break;			

		case SCREEN_STATE_MENU_EQUIPMENT_MAXSPEEDLIMIT_FUNC_TOP:		
		case SCREEN_STATE_MENU_EQUIPMENT_MAXSPEEDLIMIT_FUNC_SET:		
		case SCREEN_STATE_MENU_EQUIPMENT_MAXSPEEDLIMIT_FUNC_COMPLETE:		
		case SCREEN_STATE_MENU_EQUIPMENT_MAXSPEEDLIMIT_FUNC_NOT_COMPLETE:
		case SCREEN_STATE_MENU_EQUIPMENT_MAXSPEEDLIMIT_FUNC_END:					
		case SCREEN_STATE_MENU_EQUIPMENT_MAXSPEEDLIMIT_SPEED_TOP:				
		case SCREEN_STATE_MENU_EQUIPMENT_MAXSPEEDLIMIT_SPEED_SET:				
		case SCREEN_STATE_MENU_EQUIPMENT_MAXSPEEDLIMIT_SPEED_SET_COMPLETE:		
		case SCREEN_STATE_MENU_EQUIPMENT_MAXSPEEDLIMIT_SPEED_SET_NOT_COMPLETE:
		case SCREEN_STATE_MENU_EQUIPMENT_MAXSPEEDLIMIT_SPEED_END:		

			if((InfoModel1.ModelInfo >= MODEL_35D_9S)&&(InfoModel1.ModelInfo <= MODEL_50D_9S))
			{
				CurScreenIndex = 205;
			}
			else
			{
				CurScreenIndex = 24;
			}
			break;

		case SCREEN_STATE_MENU_EQUIPMENT_MACHINEINFO_ECM_TOP:
		case SCREEN_STATE_MENU_EQUIPMENT_MACHINEINFO_ECM_PART_NUMBER:		
		case SCREEN_STATE_MENU_EQUIPMENT_MACHINEINFO_ECM_SERIAL_NUMBER:	
		case SCREEN_STATE_MENU_EQUIPMENT_MACHINEINFO_ECM_SW_VERSION:
		case SCREEN_STATE_MENU_EQUIPMENT_MACHINEINFO_CLUSTER_TOP:	
		case SCREEN_STATE_MENU_EQUIPMENT_MACHINEINFO_CLUSTER_PART_NUMBER:		
		case SCREEN_STATE_MENU_EQUIPMENT_MACHINEINFO_CLUSTER_SERIAL_NUMBER:	
		case SCREEN_STATE_MENU_EQUIPMENT_MACHINEINFO_CLUSTER_SW_VERSION:			
		case SCREEN_STATE_MENU_EQUIPMENT_MACHINEINFO_CLUSTER_DETAIL_HIDDEN:
		case SCREEN_STATE_MENU_EQUIPMENT_MACHINEINFO_RMCU_TOP:	
		case SCREEN_STATE_MENU_EQUIPMENT_MACHINEINFO_RMCU_SERIAL_NUMBER:
		case SCREEN_STATE_MENU_EQUIPMENT_MACHINEINFO_RMCU_SW_VERSION: 
			CurScreenIndex = 25;
			break;			
		case SCREEN_STATE_MENU_EQUIPMENT_CLUTCHPROTECTION_SET:			
			CurScreenIndex = 185;
			break;			
		case SCREEN_STATE_MENU_EQUIPMENT_ZEROSTART_MODE_TOP:		
		case SCREEN_STATE_MENU_EQUIPMENT_ZEROSTART_ACCEL_TOP:
		case SCREEN_STATE_MENU_EQUIPMENT_ZEROSTART_MODE_SET:	
			CurScreenIndex = 186;
			break;			

		case SCREEN_STATE_MENU_EQUIPMENT_SEATBELTINTERLOCK_SET:
			CurScreenIndex = 189;
			break;		                        
                        
        case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_MODE_TOP:
        case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_MODE_SET:
        case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_MODE_COMPLETE:
        case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_MODE_NOT_COMPLETE:
        case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_MODE_END:
        case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_SPEED_TOP:
        case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_SPEED_UP_TOP:
        case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_SPEED_UP_END:
        case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_SPEED_DOWN_TOP:
        case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_SPEED_DOWN_END:
			
		case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_OVERLAP_TOP:
        case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_OVERLAP_UP_TOP:
		case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_OVERLAP_UP_END:		
		case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_OVERLAP_DOWN_TOP:
		case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_OVERLAP_DOWN_END:

		case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_SR_TOP:
        case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_SR_UP_TOP:
		case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_SR_UP_END:		
		case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_SR_DOWN_TOP:
		case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_SR_DOWN_END:
            CurScreenIndex = 190;
			break;	
		
		case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_SPEED_UP_SET:	
			CurScreenIndex = 191;
			break;			
		case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_SPEED_DOWN_SET:			
			CurScreenIndex = 192;
			break;

		case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_OVERLAP_UP_SET:
		case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_OVERLAP_DOWN_SET:
			CurScreenIndex = 199;
			break;

		case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_SR_UP_SET:
		case SCREEN_STATE_MENU_EQUIPMENT_AUTOSHIFT_SR_DOWN_SET:
			CurScreenIndex = 206;
			break;

		case SCREEN_STATE_MENU_EQUIPMENT_ZEROSTART_ACCEL_SET:		
			CurScreenIndex = 230;	//++, 230202 ysm, FSCU 200->230
			break;			

		case SCREEN_STATE_MENU_EQUIPMENT_RMCU_STEP_0:		
		case SCREEN_STATE_MENU_EQUIPMENT_RMCU_STEP_1:						
		case SCREEN_STATE_MENU_EQUIPMENT_RMCU_STEP_2:		
		case SCREEN_STATE_MENU_EQUIPMENT_RMCU_STEP_3:									
		case SCREEN_STATE_MENU_EQUIPMENT_RMCU_STEP_4:									
		case SCREEN_STATE_MENU_EQUIPMENT_RMCU_STEP_5:		
		case SCREEN_STATE_MENU_EQUIPMENT_RMCU_STEP_A:
			CurScreenIndex = 214;
			break;		
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_POSITION_TOP:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_DEADZONE_TOP:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_TOP:
			CurScreenIndex = 215;
			break;
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_POSITION_LIFT_TOP:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_POSITION_TILT_TOP:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_POSITION_AUX1_TOP:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_POSITION_AUX2_TOP:	
			CurScreenIndex = 216;
			break;
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_POSITION_LIFT_SET:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_POSITION_LIFT_POPUP:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_DEADZONE_LIFT_SET:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_DEADZONE_LIFT_POPUP:			
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_LIFT_UP_TOP:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_LIFT_DOWN_TOP:
			CurScreenIndex = 219;
			break;
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_POSITION_TILT_SET:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_POSITION_TILT_POPUP:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_DEADZONE_TILT_SET:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_DEADZONE_TILT_POPUP:			
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_TILT_A_TOP:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_TILT_B_TOP:
			CurScreenIndex = 220;
			break;			
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_POSITION_AUX1_SET:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_POSITION_AUX1_POPUP:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_DEADZONE_AUX1_SET:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_DEADZONE_AUX1_POPUP:			
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_AUX1_A_TOP:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_AUX1_B_TOP:
			CurScreenIndex = 221;
			break;		
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_POSITION_AUX2_SET:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_POSITION_AUX2_POPUP:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_DEADZONE_AUX2_SET:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_LEVER_DEADZONE_AUX2_POPUP:			
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_AUX2_A_TOP:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_AUX2_B_TOP:
			CurScreenIndex = 222;
			break;		
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_LIFT_UP_SET:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_LIFT_UP_POPUP:	
			CurScreenIndex = 223;
			break;	
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_LIFT_DOWN_SET:	
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_LIFT_DOWN_POPUP:
			CurScreenIndex = 224;
			break;
			
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_TILT_A_SET:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_TILT_A_POPUP: 
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_AUX1_A_SET:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_AUX1_A_POPUP: 
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_AUX2_A_SET:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_AUX2_A_POPUP: 	
			CurScreenIndex = 225;
			break;	
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_TILT_B_SET:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_TILT_B_POPUP: 
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_AUX1_B_SET:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_AUX1_B_POPUP: 
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_AUX2_B_SET:
		case SCREEN_STATE_MENU_EQUIPMENT_FINGERTIP_VALVE_SETTING_AUX2_B_POPUP:	
			CurScreenIndex = 226;
			break;	


			
		

	}
}

void DisplayListTitleMaintenance()
{
	switch(ScreenIndex)
	{
		case SCREEN_STATE_MENU_MAINTENANCE_USERPWCHANGE_CURRENT_POPUP:
		case SCREEN_STATE_MENU_MAINTENANCE_USERPWCHANGE_NEW_POPUP:					
		case SCREEN_STATE_MENU_MAINTENANCE_USERPWCHANGE_RETYPE_POPUP:		
			return;
	}

	switch(ScreenIndex)
	{
		case SCREEN_STATE_MENU_MAINTENANCE_TOP:								
			CurScreenIndex = 14;
			break;
		case SCREEN_STATE_MENU_MAINTENANCE_PW:									
			CurScreenIndex = 1;
			break;
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_TOP:		
		case SCREEN_STATE_MENU_MAINTENANCE_SIGNALSTATUS_TOP:						
		case SCREEN_STATE_MENU_MAINTENANCE_USERPWCHANGE_TOP:						
		case SCREEN_STATE_MENU_MAINTENANCE_MANAGEMENT_TOP:
			CurScreenIndex = 16;
			break;
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_ECM_TOP:	
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_ECM_CURRENT_TOP:				
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_ECM_LOGGED_TOP:				
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_ECM_LOGGED_DELETE_TOP:
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_FLT_TOP:	
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_FLT_CURRENT_TOP:				
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_FLT_LOGGED_TOP:				
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_FLT_LOGGED_DELETE_TOP:		
		//++, 221129 ysm, FSCU
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_FSCU_TOP:	
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_FSCU_CURRENT_TOP:				
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_FSCU_LOGGED_TOP:				
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_FSCU_LOGGED_DELETE_TOP:	
		//--, 221129 ysm, FSCU	
			CurScreenIndex = 67;
			break;
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_ECM_CURRENT_LIST:			
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_ECM_CURRENT_DETAIL:		
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_FLT_CURRENT_LIST:			
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_FLT_CURRENT_DETAIL:		
		//++, 221129 ysm, FSCU
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_FSCU_CURRENT_LIST:			
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_FSCU_CURRENT_DETAIL:	
		//--, 221129 ysm, FSCU	
			CurScreenIndex = 71;
			break;
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_ECM_LOGGED_LIST:				
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_ECM_LOGGED_DETAIL:		
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_FLT_LOGGED_LIST:				
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_FLT_LOGGED_DETAIL:	
		//++, 221129 ysm, FSCU	
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_FSCU_LOGGED_LIST:				
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_FSCU_LOGGED_DETAIL:	
		//--, 221129 ysm, FSCU	
			CurScreenIndex = 72;
			break;
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_ECM_LOGGED_DELETE:
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_FLT_LOGGED_DELETE:
		//++, 221129 ysm, FSCU
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_FSCU_LOGGED_DELETE:
		//--, 221129 ysm, FSCU	
		case SCREEN_STATE_MENU_MAINTENANCE_FAULTHISTORY_END:						
			CurScreenIndex = 73;
			break;
		case SCREEN_STATE_MENU_MAINTENANCE_MANAGEMENT_LIST:
			CurScreenIndex = 68;
			break;
		case SCREEN_STATE_MENU_MAINTENANCE_MANAGEMENT_LIST_HISTORY:
		case SCREEN_STATE_MENU_MAINTENANCE_MANAGEMENT_LIST_REPLACE:
		case SCREEN_STATE_MENU_MAINTENANCE_MANAGEMENT_LIST_CYCLE:
			if(gMaintenanceItem < MAINTENANCE_LPG_VAPORIZER)
				CurScreenIndex = INDEX_STR_MANAGEMENT+gMaintenanceItem;
			else
			{	
				 if(gMaintenanceItem == MAINTENANCE_LPG_VAPORIZER)
				 	CurScreenIndex = INDEX_STR_MANAGEMENT_LPG_VAPORIZE_COOLANT_HOSE;
				 else if(gMaintenanceItem == MAINTENANCE_SPARK_PLUG)
				 	CurScreenIndex = INDEX_STR_MANAGEMENT_SPARK_PLUG;
				 else if(gMaintenanceItem == MAINTENANCE_LOCK_OFF_VALVE_FILTER)
				 	CurScreenIndex = INDEX_STR_MANAGEMENT_LOCK_OFF_VALVE_FILTER;
				 else
				 	CurScreenIndex = INDEX_STR_MANAGEMENT_BRAKE_COOLING_OIL_FILTER;
			}
			break;
		case SCREEN_STATE_MENU_MAINTENANCE_MANAGEMENT_HISTORY_DETAIL:
			CurScreenIndex = 155;
			break;
		case SCREEN_STATE_MENU_MAINTENANCE_MANAGEMENT_REPLACE_POPUP:
			CurScreenIndex = 156;
			break;
		case SCREEN_STATE_MENU_MAINTENANCE_MANAGEMENT_CHANGE_CYCLE:
		case SCREEN_STATE_MENU_MAINTENANCE_MANAGEMENT_CYCLE_POPUP:
			CurScreenIndex = 157;
			break;
		case SCREEN_STATE_MENU_MAINTENANCE_SIGNALSTATUS_ANALOG_TOP:				
		case SCREEN_STATE_MENU_MAINTENANCE_SIGNALSTATUS_DIGITALINPUT_TOP:				
		case SCREEN_STATE_MENU_MAINTENANCE_SIGNALSTATUS_DIGITALOUTPUT_TOP:				
			CurScreenIndex = 69;
			break;
		case SCREEN_STATE_MENU_MAINTENANCE_SIGNALSTATUS_ANALOG_LIST:			
		case SCREEN_STATE_MENU_MAINTENANCE_SIGNALSTATUS_ANALOG_END:				
			CurScreenIndex = 79;
			break;
		case SCREEN_STATE_MENU_MAINTENANCE_SIGNALSTATUS_DIGITALINPUT_LIST:			
		case SCREEN_STATE_MENU_MAINTENANCE_SIGNALSTATUS_DIGITALINPUT_END:				
			CurScreenIndex = 80;
			break;
		case SCREEN_STATE_MENU_MAINTENANCE_SIGNALSTATUS_DIGITALOUTPUT_LIST:			
		case SCREEN_STATE_MENU_MAINTENANCE_SIGNALSTATUS_DIGITALOUTPUT_END:				
		case SCREEN_STATE_MENU_MAINTENANCE_SIGNALSTATUS_END:						
			CurScreenIndex = 81;
			break;
		case SCREEN_STATE_MENU_MAINTENANCE_USERPWCHANGE_CURRENT:					
			CurScreenIndex = 76;
			break;
		case SCREEN_STATE_MENU_MAINTENANCE_USERPWCHANGE_NEW:						
			CurScreenIndex = 77;
			break;
		case SCREEN_STATE_MENU_MAINTENANCE_USERPWCHANGE_RETYPE:				
			CurScreenIndex = 78;
			break;
		case SCREEN_STATE_MENU_MAINTENANCE_USERPWCHANGE_COMPLETE:			
		case SCREEN_STATE_MENU_MAINTENANCE_USERPWCHANGE_NOT_COMPLETE:	
			CurScreenIndex = 70;
			break;
	}
}

void DisplayListTitleDsiplaySetting()
{
	switch(ScreenIndex)
	{
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_CURRENT_POPUP:
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_NEW_POPUP:					
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_RETYPE_POPUP:		
			return;
	}

	switch(ScreenIndex)
	{
		case SCREEN_STATE_MENU_DISPLAYSETTING_TOP:										
			CurScreenIndex = 14;
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TOP:
		case SCREEN_STATE_MENU_DISPLAYSETTING_LCD_BRIGHTNESS_TOP:				
		case SCREEN_STATE_MENU_DISPLAYSETTING_LED_BRIGHTNESS_TOP:				
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_TOP:							
		case SCREEN_STATE_MENU_DISPLAYSETTING_LANGUAGE_TOP:						
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_TOP:					
			CurScreenIndex = 17;
			break;
			
		case SCREEN_STATE_MENU_DISPLAYSETTING_LCD_BRIGHTNESS_CHANGE:			
		case SCREEN_STATE_MENU_DISPLAYSETTING_LCD_BRIGHTNESS_END:			
			CurScreenIndex = 83;
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_LED_BRIGHTNESS_CHANGE:			
		case SCREEN_STATE_MENU_DISPLAYSETTING_LED_BRIGHTNESS_END:			
			CurScreenIndex = 175;
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_SPEED_TOP:				
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_WEIGHT_TOP:			
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_TEMPERATURE_TOP:	
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_PRESSURE_TOP:				
			CurScreenIndex = 84;
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_SPEED_CHANGE:			
			CurScreenIndex = 87;
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_WEIGHT_CHANGE:		
			CurScreenIndex = 88;
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_TEMPERATURE_CHANGE:	
			CurScreenIndex = 89;
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_PRESSURE_CHANGE:		
			CurScreenIndex = 90;
			break;

		case SCREEN_STATE_MENU_DISPLAYSETTING_LANGUAGE_CHANGE:					
		case SCREEN_STATE_MENU_DISPLAYSETTING_LANGUAGE_END:						
			CurScreenIndex = 85;
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_CURRENT:			
			CurScreenIndex = 91;
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_NEW:					
			CurScreenIndex = 92;
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_RETYPE:			
			CurScreenIndex = 93;
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_COMPLETE:		
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_NOT_COMPLETE:
			CurScreenIndex = 86;
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_TOP:
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_TOP:
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_END:
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_SETAMPM:
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_SETHOUR:
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_SETMINUTE:
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_END:
			CurScreenIndex = 82;
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_SETYEAR:
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_SETMONTH:
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_SETDAY:
			CurScreenIndex = 174;
			break;
		
		//////////////////////////////////////////////////////////////////////////////////////				
	}
}
