#include "FLV_Cluster_APP.h"

extern UCHAR nBrightnessLevel;

extern EEPROM_DISPLAY_DATA OldInfoDisplaySetting;

extern RTC_HandleTypeDef hrtc;
extern st_DATA_RTC RTC_Data;
extern st_DATA_RTC sChangeRTC;
unsigned char ChangeAMPMStatus;

UCHAR MaxDate = 31;

void CheckDate(USHORT Year, UCHAR Month)
{		
	USHORT _Year = Year+2000;
	
	switch(Month)
	{
		case 1: case 3: case 5: case 7: case 8: case 10: case 12:
			MaxDate = 31;
			break;
		case 4: case 6: case 9: case 11:
			MaxDate = 30;
			break;
		case 2:
			if(_Year % 400 == 0)
				MaxDate = 29;
			else if(_Year % 100 == 0)
				MaxDate = 28;
			else if(_Year % 4 == 0)
				MaxDate = 29;
			else
				MaxDate = 28;
			break;
	}
}

void DisplayMenuDisplaySetting()
{
	switch(ScreenIndex)
	{
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_CURRENT:			
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_NEW:					
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_RETYPE:			
			if(OldScreenIndex != ScreenIndex)
			{
				InitializeDisplayPassword(NUMBER_INFO_ENTER);
				DrawMenuFull();
			}
			break;		
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_CURRENT_POPUP:
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_NEW_POPUP:					
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_RETYPE_POPUP:		
			DisplayPasswordPopup();
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TOP:
		case SCREEN_STATE_MENU_DISPLAYSETTING_LCD_BRIGHTNESS_TOP:				
		case SCREEN_STATE_MENU_DISPLAYSETTING_LED_BRIGHTNESS_TOP:				
			if(OldScreenIndex != ScreenIndex)
			{
				if((OldScreenIndex != SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TOP)
					&& (OldScreenIndex != SCREEN_STATE_MENU_DISPLAYSETTING_LCD_BRIGHTNESS_TOP)
					&& (OldScreenIndex != SCREEN_STATE_MENU_DISPLAYSETTING_LED_BRIGHTNESS_TOP))
				{
					SetListString3(82, 83, 175);
					DisplayListAll(((ScreenIndex&0x0F000000)>>24));
					DisplayListPage(1,2);
					DrawMenuFull();
				}
				else if(OldScreenIndex != ScreenIndex)
				{
					DisplayList(((ScreenIndex&0x0F000000)>>24));
				}
			}
			break;			
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_TOP:							
		case SCREEN_STATE_MENU_DISPLAYSETTING_LANGUAGE_TOP:	
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_TOP:		
			if((OldScreenIndex != SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_TOP)
				&& (OldScreenIndex != SCREEN_STATE_MENU_DISPLAYSETTING_LANGUAGE_TOP)
				&& (OldScreenIndex != SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_TOP))
			{
				SetListString3(84,85,86);
				DisplayListAll(((ScreenIndex&0x0F000000)>>24)-3);
				DisplayListPage(2,2);
				DrawMenuFull();
			}
			else if(OldScreenIndex != ScreenIndex)
			{
				DisplayList(((ScreenIndex&0x0F000000)>>24)-3);
			}
			break;			

		case SCREEN_STATE_MENU_DISPLAYSETTING_LCD_BRIGHTNESS_CHANGE:			
		case SCREEN_STATE_MENU_DISPLAYSETTING_LCD_BRIGHTNESS_END:				
		case SCREEN_STATE_MENU_DISPLAYSETTING_LED_BRIGHTNESS_CHANGE:			
		case SCREEN_STATE_MENU_DISPLAYSETTING_LED_BRIGHTNESS_END:				
			DisplayBrightness();
			break;
			
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_SPEED_TOP:				
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_SPEED_CHANGE:			
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_SPEED_END:				
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_WEIGHT_TOP:			
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_WEIGHT_CHANGE:		
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_WEIGHT_END:				
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_TEMPERATURE_TOP:	
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_TEMPERATURE_CHANGE:	
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_TEMPERATURE_END:		
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_PRESSURE_TOP:				
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_PRESSURE_CHANGE:		
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_PRESSURE_END:				
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_END:					
			DisplayUnitSet();
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_LANGUAGE_CHANGE:					
		case SCREEN_STATE_MENU_DISPLAYSETTING_LANGUAGE_END:			
			if((OldScreenIndex != ScreenIndex) || (OldCurserIndex != CurserIndex))
				DisplayLanguageList();
			break;
	
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_COMPLETE:		
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_NOT_COMPLETE:
			DisplayPopupStringComplete();
			break;	
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_TOP:
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_SETYEAR:
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_SETMONTH:
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_SETDAY:
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_END:
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_TOP:
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_SETAMPM:
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_SETHOUR:
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_SETMINUTE:
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_END:
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_END:
			DisplayClock();
			break;
	}

}

///////////////////////////////////////////////////////////////////////////
void LeftKeyEventMenuDisplaySetting()
{
	switch(ScreenIndex)
	{
		case SCREEN_STATE_MENU_DISPLAYSETTING_TOP:							
			SetScreenIndex(SCREEN_STATE_MENU_MAINTENANCE_TOP);
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_CURRENT:			
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_NEW:					
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_RETYPE:			
			LeftKeyEventNumberInput();
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TOP:				
			SetScreenIndex(SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_TOP);
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_LCD_BRIGHTNESS_TOP:
		case SCREEN_STATE_MENU_DISPLAYSETTING_LED_BRIGHTNESS_TOP:
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_TOP:		
		case SCREEN_STATE_MENU_DISPLAYSETTING_LANGUAGE_TOP:					
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_TOP:						
			SetScreenIndex(((((ScreenIndex&0xFF000000)>>24)-1)<<24));
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_LCD_BRIGHTNESS_CHANGE:			
		case SCREEN_STATE_MENU_DISPLAYSETTING_LED_BRIGHTNESS_CHANGE:			
			CurserIndex = CURSER_UP_LEFT;
			if(nBrightnessLevel > BRIGHTNESS_MIN)
				nBrightnessLevel--;
			if(ScreenIndex == SCREEN_STATE_MENU_DISPLAYSETTING_LCD_BRIGHTNESS_CHANGE)
				InfoDisplaySetting.LCDBrightnessLevel = nBrightnessLevel;
			else
				InfoDisplaySetting.LEDBrightnessLevel = nBrightnessLevel;
			KeyUIcnt100ms = 0;
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_SPEED_TOP:				
			SetScreenIndex(SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_PRESSURE_TOP);
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_WEIGHT_TOP:			
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_TEMPERATURE_TOP:	
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_PRESSURE_TOP:				
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_TOP:
			SetScreenIndex(((((ScreenIndex&0xFFF00000)>>20)-1)<<20));
			break;

		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_SPEED_CHANGE:			
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_WEIGHT_CHANGE:		
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_TEMPERATURE_CHANGE:	
		case SCREEN_STATE_MENU_DISPLAYSETTING_LANGUAGE_CHANGE:					
			if(CurserIndex == 0)
				CurserIndex = 1;
			else
				CurserIndex = 0;
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_PRESSURE_CHANGE:
			if(CurserIndex > 0)
				CurserIndex--;
			else
				CurserIndex = 2;
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_TOP:
			SetScreenIndex(SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_TOP);
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_SETYEAR:
			CurserIndex = CURSER_UP_LEFT;
			if(sChangeRTC.Year> 0)
				sChangeRTC.Year--;
			else
				sChangeRTC.Year = 99;
			KeyUIcnt100ms = 0;
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_SETMONTH:
			CurserIndex = CURSER_UP_LEFT;
			if(sChangeRTC.Month> 1)
				sChangeRTC.Month--;
			else
				sChangeRTC.Month = 12;
			KeyUIcnt100ms = 0;
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_SETDAY:
			CurserIndex = CURSER_UP_LEFT;
			if(sChangeRTC.Date> 1)
				sChangeRTC.Date--;
			else 
				sChangeRTC.Date = MaxDate;
			KeyUIcnt100ms = 0;
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_SETHOUR:
			CurserIndex = CURSER_UP_LEFT;
			if(sChangeRTC.Hours > 0)
				sChangeRTC.Hours--;
			else
				sChangeRTC.Hours = 23;
			KeyUIcnt100ms = 0;
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_SETMINUTE:
			CurserIndex = CURSER_UP_LEFT;
			if(sChangeRTC.Minutes> 0)
				sChangeRTC.Minutes--;
			else
				sChangeRTC.Minutes = 59;
			KeyUIcnt100ms = 0;
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_SETAMPM:
			CurserIndex = CURSER_UP_LEFT;
			if(ChangeAMPMStatus == CLOCK_AM)
				ChangeAMPMStatus = CLOCK_PM;
			else
				ChangeAMPMStatus = CLOCK_AM;
			KeyUIcnt100ms = 0;
			break;
	}

}

void RightKeyEventMenuDisplaySetting()
{
	switch(ScreenIndex)
	{
		case SCREEN_STATE_MENU_DISPLAYSETTING_TOP:		
			SetScreenIndex(SCREEN_STATE_MENU_EQUIPMENT_TOP);
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_CURRENT:			
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_NEW:					
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_RETYPE:			
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_END:					
			RightKeyEventNumberInput();
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TOP:
		case SCREEN_STATE_MENU_DISPLAYSETTING_LCD_BRIGHTNESS_TOP:				
		case SCREEN_STATE_MENU_DISPLAYSETTING_LED_BRIGHTNESS_TOP:				
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_TOP:							
		case SCREEN_STATE_MENU_DISPLAYSETTING_LANGUAGE_TOP:					
			SetScreenIndex(((((ScreenIndex&0xFF000000)>>24)+1)<<24));
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_TOP:						
			SetScreenIndex(SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TOP);
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_LCD_BRIGHTNESS_CHANGE:			
		case SCREEN_STATE_MENU_DISPLAYSETTING_LED_BRIGHTNESS_CHANGE:			
			CurserIndex = CURSER_DOWN_RIGHT;
			if(nBrightnessLevel < BRIGHTNESS_MAX)
				nBrightnessLevel++;
			if(ScreenIndex == SCREEN_STATE_MENU_DISPLAYSETTING_LCD_BRIGHTNESS_CHANGE)
				InfoDisplaySetting.LCDBrightnessLevel = nBrightnessLevel;
			else
				InfoDisplaySetting.LEDBrightnessLevel = nBrightnessLevel;
			KeyUIcnt100ms = 0;
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_SPEED_TOP:				
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_WEIGHT_TOP:			
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_TEMPERATURE_TOP:	
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_TOP:
			SetScreenIndex(((((ScreenIndex&0xFFF00000)>>20)+1)<<20));
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_PRESSURE_TOP:				
			SetScreenIndex(SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_SPEED_TOP);
			break;

		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_SPEED_CHANGE:			
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_WEIGHT_CHANGE:		
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_TEMPERATURE_CHANGE:	
		case SCREEN_STATE_MENU_DISPLAYSETTING_LANGUAGE_CHANGE:					
			if(CurserIndex == 0)
				CurserIndex = 1;
			else
				CurserIndex = 0;
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_PRESSURE_CHANGE:
			if(CurserIndex < 2)
				CurserIndex++;
			else
				CurserIndex = 0;
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_TOP:
			SetScreenIndex(SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_TOP);
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_SETYEAR:
			CurserIndex = CURSER_DOWN_RIGHT;
			if(sChangeRTC.Year < 255)
				sChangeRTC.Year++;
			else
				sChangeRTC.Year = 0;
			KeyUIcnt100ms = 0;
			break;				
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_SETMONTH:
			CurserIndex = CURSER_DOWN_RIGHT;
			if(sChangeRTC.Month< 12)
				sChangeRTC.Month++;
			else
				sChangeRTC.Month = 1;
			KeyUIcnt100ms = 0;
			break;				
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_SETDAY:
			CurserIndex = CURSER_DOWN_RIGHT;
			if(sChangeRTC.Date< MaxDate)
				sChangeRTC.Date++;
			else 
				sChangeRTC.Date = 1;
			KeyUIcnt100ms = 0;
			break;				
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_SETHOUR:
			CurserIndex = CURSER_DOWN_RIGHT;
			if(sChangeRTC.Hours < 23)
				sChangeRTC.Hours++;
			else
				sChangeRTC.Hours = 0;
			KeyUIcnt100ms = 0;
			break;				
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_SETMINUTE:
			CurserIndex = CURSER_DOWN_RIGHT;
			if(sChangeRTC.Minutes< 59)
				sChangeRTC.Minutes++;
			else
				sChangeRTC.Minutes = 0;
			KeyUIcnt100ms = 0;
			break;				
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_SETAMPM:
			CurserIndex = CURSER_DOWN_RIGHT;
			if(ChangeAMPMStatus == CLOCK_AM)
				ChangeAMPMStatus = CLOCK_PM;
			else
				ChangeAMPMStatus = CLOCK_AM;
			KeyUIcnt100ms = 0;
			break;
	}

}

void ESCKeyEventMenuDisplaySetting()
{
	switch(ScreenIndex)
	{
		case SCREEN_STATE_MENU_DISPLAYSETTING_TOP:							
			SetScreenIndex(SCREEN_STATE_MAIN_TOP);
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_CURRENT:			
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_NEW:					
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_RETYPE:		
			ESCKeyEventNumberInput();
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_CURRENT_POPUP:
			SetScreenIndex(ScreenIndex&0xFFFFFFF0);
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_NEW_POPUP:					
			SetScreenIndex(SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_NEW);
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_RETYPE_POPUP:		
			SetScreenIndex(SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_RETYPE);
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_LCD_BRIGHTNESS_TOP:				
		case SCREEN_STATE_MENU_DISPLAYSETTING_LED_BRIGHTNESS_TOP:				
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_TOP:							
		case SCREEN_STATE_MENU_DISPLAYSETTING_LANGUAGE_TOP:						
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_TOP:					
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TOP:
			SetScreenIndex(SCREEN_STATE_MENU_DISPLAYSETTING_TOP);
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_LCD_BRIGHTNESS_CHANGE:			
		case SCREEN_STATE_MENU_DISPLAYSETTING_LED_BRIGHTNESS_CHANGE:		
			if(ScreenIndex == SCREEN_STATE_MENU_DISPLAYSETTING_LCD_BRIGHTNESS_CHANGE)
			{
				InfoDisplaySetting.LCDBrightnessLevel = OldInfoDisplaySetting.LCDBrightnessLevel;
				ControlLCDBrightnessLevel(InfoDisplaySetting.LCDBrightnessLevel);
			}
			else if(ScreenIndex == SCREEN_STATE_MENU_DISPLAYSETTING_LED_BRIGHTNESS_CHANGE)
			{
				InfoDisplaySetting.LEDBrightnessLevel = OldInfoDisplaySetting.LEDBrightnessLevel;
				ControlLEDBrightnessLevel(InfoDisplaySetting.LEDBrightnessLevel);
			}
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_SPEED_TOP:				
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_WEIGHT_TOP:			
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_TEMPERATURE_TOP:	
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_PRESSURE_TOP:				
		case SCREEN_STATE_MENU_DISPLAYSETTING_LANGUAGE_CHANGE:			
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_TOP:
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_TOP:
			SetScreenIndex(ScreenIndex&0xFF000000);
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_SPEED_CHANGE:			
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_WEIGHT_CHANGE:		
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_TEMPERATURE_CHANGE:	
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_PRESSURE_CHANGE:		
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_SETYEAR:
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_SETAMPM:
			SetScreenIndex(ScreenIndex&0xFFF00000);
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_COMPLETE:		
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_NOT_COMPLETE:
			SetScreenIndex(SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_TOP);
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_SETMONTH:
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_SETDAY:
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_SETHOUR:
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_SETMINUTE:
			SetScreenIndex(((((ScreenIndex&0xFFFF0000)>>16)-1)<<16));
			break;
	}
}

void EnterKeyEventMenuDisplaySetting()
{
	st_DATA_RTC temp_RTC;

	switch(ScreenIndex)
	{
		case SCREEN_STATE_MENU_DISPLAYSETTING_TOP:			
			SetScreenIndex(SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TOP);
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_CURRENT:			
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_NEW:					
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_RETYPE:			
			EnterKeyEventNumberInput();
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_CURRENT_POPUP:
			SetScreenIndex(ScreenIndex&0xFFFFFFF0);
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_LCD_BRIGHTNESS_TOP:			
		case SCREEN_STATE_MENU_DISPLAYSETTING_LED_BRIGHTNESS_TOP:			
			CurserIndex = CURSER_NONE;
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_SPEED_TOP:
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_WEIGHT_TOP:
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_TEMPERATURE_TOP:
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_PRESSURE_TOP:
		case SCREEN_STATE_MENU_DISPLAYSETTING_LANGUAGE_TOP:		
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TOP:
			OldCurserIndex = 0xFF;
			
			if(ScreenIndex == SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_SPEED_TOP)
				CurserIndex = InfoDisplaySetting.SpeedUnit;
			else if(ScreenIndex == SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_WEIGHT_TOP)
				CurserIndex = InfoDisplaySetting.WeightUnit;
			else if(ScreenIndex == SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_TEMPERATURE_TOP)
				CurserIndex = InfoDisplaySetting.TemperatureUnit;
			else if(ScreenIndex == SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_PRESSURE_TOP)
				CurserIndex = InfoDisplaySetting.PressureUnit;
			else if(ScreenIndex == SCREEN_STATE_MENU_DISPLAYSETTING_LANGUAGE_TOP)
				CurserIndex = InfoDisplaySetting.Language;
			else if(ScreenIndex == SCREEN_STATE_MENU_DISPLAYSETTING_LCD_BRIGHTNESS_TOP)
				nBrightnessLevel = InfoDisplaySetting.LCDBrightnessLevel;
			else if(ScreenIndex == SCREEN_STATE_MENU_DISPLAYSETTING_LED_BRIGHTNESS_TOP)
				nBrightnessLevel = InfoDisplaySetting.LEDBrightnessLevel;
			
			if((ScreenIndex & 0xFF000000) == SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_TOP)
				SetScreenIndex(ScreenIndex | 0x00010000);
			else
				SetScreenIndex(ScreenIndex | 0x00100000);
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_TOP:
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_TOP:				
			SetScreenIndex(ScreenIndex | 0x00100000);
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_SPEED_CHANGE:
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_WEIGHT_CHANGE:
		case SCREEN_STATE_MENU_DISPLAYSETTING_LCD_BRIGHTNESS_CHANGE:
		case SCREEN_STATE_MENU_DISPLAYSETTING_LED_BRIGHTNESS_CHANGE:
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_TEMPERATURE_CHANGE:
		case SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_PRESSURE_CHANGE:
		case SCREEN_STATE_MENU_DISPLAYSETTING_LANGUAGE_CHANGE:					
			if(ScreenIndex == SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_SPEED_CHANGE)
				InfoDisplaySetting.SpeedUnit = CurserIndex;
			else if(ScreenIndex == SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_WEIGHT_CHANGE)
				InfoDisplaySetting.WeightUnit = CurserIndex;
			else if(ScreenIndex == SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_TEMPERATURE_CHANGE)
				InfoDisplaySetting.TemperatureUnit = CurserIndex;
			else if(ScreenIndex == SCREEN_STATE_MENU_DISPLAYSETTING_UNIT_PRESSURE_CHANGE)
				InfoDisplaySetting.PressureUnit = CurserIndex;
			else if(ScreenIndex == SCREEN_STATE_MENU_DISPLAYSETTING_LANGUAGE_CHANGE)
				InfoDisplaySetting.Language= CurserIndex;
			SaveDisplaySetting();
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_COMPLETE:		
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_NOT_COMPLETE:
			SetScreenIndex(SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_TOP);
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_NEW_POPUP:					
			SetScreenIndex(SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_NEW);
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_RETYPE_POPUP:		
			SetScreenIndex(SCREEN_STATE_MENU_DISPLAYSETTING_ESLPWCHANGE_RETYPE);
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_TOP:
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_TOP:
			read_RTC(&RTC_Data);
			sChangeRTC = RTC_Data;
			SetScreenIndex(ScreenIndex | 0x00010000);
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_SETMONTH:
			CheckDate(sChangeRTC.Year, sChangeRTC.Month);
			if(sChangeRTC.Date > MaxDate)
				sChangeRTC.Date = MaxDate;
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_SETAMPM:
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_SETHOUR:
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_SETYEAR:
			SetScreenIndex(((((ScreenIndex&0xFFFF0000)>>16)+1)<<16));
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_DATE_SETDAY:
			RTC_Data = sChangeRTC;			
			temp_RTC = Calculate_RTC_LHO_Applied(&RTC_Data, HCESPN.H951, 1);
			write_RTC(&temp_RTC);
			SetScreenIndex(ScreenIndex&0xFFF00000);
			break;
		case SCREEN_STATE_MENU_DISPLAYSETTING_CLOCK_TIME_SETMINUTE:
			if(sChangeRTC.Hours >= 12)
				sChangeRTC.Hours -= 12;
			if(ChangeAMPMStatus == CLOCK_PM)
				sChangeRTC.Hours += 12;
			sChangeRTC.Seconds = 0;

			RTC_Data = sChangeRTC;	
			temp_RTC = Calculate_RTC_LHO_Applied(&RTC_Data, HCESPN.H951, 1);
			write_RTC(&temp_RTC);
			SetScreenIndex(ScreenIndex&0xFFF00000);
			break;
	}

}
